"""EuroAgent SFT corpus prep — DE + EN, agentic + tool-calling.

Sister script to `dllm.data.prepare`. Where `prepare` builds the pretraining
corpus (5 B tokens, raw text), this builds the post-training corpus:
multi-turn conversations with structured tool calls, rendered to our canonical
ChatML schema (see `dllm.data.sft_format`), tokenized with the **same**
tokenizer that pretrained the base model (no separate BPE training).

Outputs under data/cache/sft/:
    sft_train.bin       uint16 token IDs (same vocab as train.bin)
    sft_train_mask.bin  uint8 loss-target flags, parallel to sft_train.bin
    sft_val.bin         uint16 val tokens (conversation-aligned split)
    sft_val_mask.bin    uint8 val loss-target flags
    manifest.json       per-source license / count / task-type provenance

Loss mask convention: mask[i] == 1 iff token i was generated by the assistant
(including the closing <|im_end|>). The loader is responsible for applying
the X→Y shift; the on-disk mask is *not* pre-shifted.

Compliance: each source's license is propagated to the manifest verbatim,
satisfying EU AI Act Art. 53 disclosure for SFT data the same way the
pretraining manifest does for raw text.

Requires the [data] extras (datasets + tokenizers).
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import queue as _queue
import sys
import threading
from datetime import date, datetime, timezone
from pathlib import Path
from typing import Iterator

import numpy as np

os.environ.setdefault("TOKENIZERS_PARALLELISM", "true")

from . import sft_sources as sources
from .sft_format import Conversation, render_chatml_with_mask

try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except AttributeError:
    pass


EOT_TOKEN = "<|endoftext|>"
DEFAULT_LANGS = ["de", "en"]


# Per-source per-lang **example-count** budgets (not chars — SFT is small).
# Designed for ~65k conversations ≈ 50–80M tokens, plausible 1–5 % of the
# 5 B-token pretraining corpus. Operators can override via --alloc.
#
# xLAM (Salesforce/xlam-function-calling-60k) is **gated on HuggingFace** and
# is NOT in the default mix — request access first, then add it via
# `--sources xlam <other sources>`. Glaive v2 + Hermes-FC together already
# exceed xLAM's example count for EN tool-call coverage.
DEFAULT_ALLOC_COUNT = {
    "glaive_v2":         {"en": 25_000},
    "glaive_v2_de":      {"de": 25_000},  # produced offline by scripts/translate_glaive_to_de.py
    "hermes_fc":         {"en": 15_000},
    "oasst2":            {"en":  8_000, "de": 5_000},
    "aya":               {"en":  5_000, "de": 5_000},
    "germanrag":         {"de":  5_000},  # ~3k available; primary native-DE agentic
    "avemio_german_rag": {"de": 15_000},  # native-DE RAG + agentic + FC selection (MIT)
    "hand_written":      {"en":  1_000, "de": 1_000},
}


def cache_dir() -> Path:
    here = Path(__file__).resolve().parent
    out = here.parent.parent.parent / "data" / "cache" / "sft"
    out.mkdir(parents=True, exist_ok=True)
    return out


def pretrain_tokenizer_path() -> Path:
    """SFT reuses the BPE trained for pretraining — same vocab IDs, same
    embedding table on the base model."""
    here = Path(__file__).resolve().parent
    return here.parent.parent.parent / "data" / "cache" / "tokenizer.json"


# ---------------------------------------------------------------------------
# Producer threads — one per (source, lang) pair, like prepare.py
# ---------------------------------------------------------------------------


def _parallel_producers(
    alloc: dict[str, dict[str, int]],
    langs: list[str],
    out_q: _queue.Queue,
    sentinel,
) -> list[threading.Thread]:
    pairs: list[tuple[str, str, int]] = []
    for src_name, lang_budgets in alloc.items():
        try:
            src = sources.load(src_name)
        except ValueError:
            continue
        for lang, budget in lang_budgets.items():
            if lang not in langs:
                continue
            if lang not in src.supported_langs():
                continue
            if budget <= 0:
                continue
            pairs.append((src_name, lang, budget))

    def fetch(src_name: str, lang: str, budget: int) -> None:
        try:
            src = sources.load(src_name)
            for conv in src.iter_examples(lang, budget):
                out_q.put((src_name, lang, conv))
        except Exception as e:  # noqa: BLE001
            print(f"    [warn] fetcher {src_name}/{lang} died: {e}")
        finally:
            out_q.put(sentinel)

    threads: list[threading.Thread] = []
    for src_name, lang, budget in pairs:
        t = threading.Thread(
            target=fetch,
            args=(src_name, lang, budget),
            daemon=True,
            name=f"sft-fetch-{src_name}-{lang}",
        )
        t.start()
        threads.append(t)
    return threads


# ---------------------------------------------------------------------------
# Tokenization — render Conversation, encode_batch all segments
# ---------------------------------------------------------------------------


def _encode_conversation_batch(
    convs_meta: list[tuple[str, str, Conversation]],
    tokenizer,
) -> list[tuple[str, str, list[int], list[int]]]:
    """Batch-tokenize a group of conversations.

    Returns one (src_name, lang, ids, mask) per input conv. We flatten all
    segments across the batch into one encode_batch call so the Rust impl
    can parallelize maximally; then re-emit per-conversation.
    """
    if not convs_meta:
        return []

    flat_texts: list[str] = []
    flat_targets: list[int] = []
    # Per-conv slice indices into flat_texts
    boundaries: list[int] = [0]

    for _, _, conv in convs_meta:
        segs = render_chatml_with_mask(conv)
        for text, is_target in segs:
            flat_texts.append(text)
            flat_targets.append(1 if is_target else 0)
        boundaries.append(len(flat_texts))

    encodings = tokenizer.encode_batch(flat_texts)

    out: list[tuple[str, str, list[int], list[int]]] = []
    for i, (src_name, lang, _) in enumerate(convs_meta):
        start, end = boundaries[i], boundaries[i + 1]
        ids: list[int] = []
        mask: list[int] = []
        for j in range(start, end):
            seg_ids = encodings[j].ids
            ids.extend(seg_ids)
            mask.extend([flat_targets[j]] * len(seg_ids))
        out.append((src_name, lang, ids, mask))
    return out


# ---------------------------------------------------------------------------
# Streaming writer with parallel ids + mask + conversation boundaries
# ---------------------------------------------------------------------------


class DualShardWriter:
    """Writes paired (ids: uint16, mask: uint8) streams to disk.

    Buffers in memory for ~50 M tokens (~150 MB combined) before flushing.
    Tracks conversation boundary positions so train/val can be split at a
    boundary, never mid-conversation.
    """

    def __init__(self, ids_path: Path, mask_path: Path, flush_tokens: int = 50_000_000) -> None:
        self.ids_path = ids_path
        self.mask_path = mask_path
        self._ids = np.empty(flush_tokens, dtype=np.uint16)
        self._mask = np.empty(flush_tokens, dtype=np.uint8)
        self._idx = 0
        self._cap = flush_tokens
        self._total = 0
        self._boundaries: list[int] = [0]  # cumulative token positions
        self._ids_fp = ids_path.open("wb")
        self._mask_fp = mask_path.open("wb")

    def write_conv(self, ids: list[int], mask: list[int]) -> None:
        assert len(ids) == len(mask), (len(ids), len(mask))
        i = 0
        while i < len(ids):
            room = self._cap - self._idx
            take = min(room, len(ids) - i)
            self._ids[self._idx : self._idx + take] = ids[i : i + take]
            self._mask[self._idx : self._idx + take] = mask[i : i + take]
            self._idx += take
            i += take
            if self._idx == self._cap:
                self._flush()
        # Record cumulative token position where this conversation ended.
        self._boundaries.append(self._total + self._idx)

    def _flush(self) -> None:
        if self._idx == 0:
            return
        self._ids_fp.write(self._ids[: self._idx].tobytes())
        self._mask_fp.write(self._mask[: self._idx].tobytes())
        self._total += self._idx
        self._idx = 0

    def close(self) -> tuple[int, list[int]]:
        self._flush()
        self._ids_fp.close()
        self._mask_fp.close()
        return self._total, list(self._boundaries)


def stream_tokenize_to_disk(
    alloc: dict[str, dict[str, int]],
    langs: list[str],
    tokenizer,
    ids_path: Path,
    mask_path: Path,
    batch_size: int = 64,
    queue_size: int = 256,
) -> tuple[int, dict[tuple[str, str], int], list[int]]:
    """Run producers → encode_batch → DualShardWriter end to end.

    Returns (total_tokens, per_(src,lang)_token_count, conversation_boundaries).
    Boundaries are token positions where each conversation ends; useful for
    splitting train/val at a boundary.
    """
    SENTINEL = object()
    conv_q: _queue.Queue = _queue.Queue(maxsize=queue_size)

    producers = _parallel_producers(alloc, langs, conv_q, SENTINEL)
    n_producers = len(producers)

    writer = DualShardWriter(ids_path, mask_path)
    counts: dict[tuple[str, str], int] = {}
    n_convs = 0
    last_print = 0

    sentinels_seen = 0
    batch: list[tuple[str, str, Conversation]] = []

    def drain_batch():
        nonlocal n_convs, last_print
        if not batch:
            return
        encoded = _encode_conversation_batch(batch, tokenizer)
        for src_name, lang, ids, mask in encoded:
            # Append EOT between conversations as a non-target separator.
            eot_id = tokenizer.token_to_id(EOT_TOKEN)
            assert eot_id is not None, f"{EOT_TOKEN!r} missing from tokenizer vocab"
            ids = ids + [eot_id]
            mask = mask + [0]
            writer.write_conv(ids, mask)
            counts[(src_name, lang)] = counts.get((src_name, lang), 0) + len(ids)
            n_convs += 1
        batch.clear()
        cur = writer._total + writer._idx
        if cur - last_print >= 10_000_000:
            print(f"    [sft tokenize] {n_convs:,} convs, {cur / 1e6:.1f} M tokens")
            last_print = cur

    while sentinels_seen < n_producers:
        item = conv_q.get()
        if item is SENTINEL:
            sentinels_seen += 1
            continue
        batch.append(item)
        if len(batch) >= batch_size:
            drain_batch()
    drain_batch()

    for t in producers:
        t.join(timeout=2.0)

    total, boundaries = writer.close()
    return total, counts, boundaries


# ---------------------------------------------------------------------------
# Train/val split at a conversation boundary
# ---------------------------------------------------------------------------


def split_at_boundary(
    train_ids: Path,
    train_mask: Path,
    val_ids: Path,
    val_mask: Path,
    boundaries: list[int],
    val_fraction: float = 0.02,
) -> tuple[int, int]:
    """Split (ids, mask) at the conv boundary closest to (1 - val_fraction).

    Never splits mid-conversation — keeps every conversation atomic on
    whichever side it lands. Returns (train_tokens, val_tokens).
    """
    total = boundaries[-1] if boundaries else 0
    if total == 0:
        return 0, 0

    target = int(total * (1 - val_fraction))
    # boundaries[0] = 0; pick the boundary closest to target (but never the very
    # first, which would put all data in val).
    candidates = boundaries[1:]
    if not candidates:
        return total, 0
    split_pos = min(candidates, key=lambda p: abs(p - target))
    # Guard against degenerate edges (all in train, all in val).
    split_pos = max(1, min(total - 1, split_pos)) if total > 1 else total

    ids_arr = np.memmap(train_ids, dtype=np.uint16, mode="r")
    mask_arr = np.memmap(train_mask, dtype=np.uint8, mode="r")
    val_ids_slice = np.array(ids_arr[split_pos:], dtype=np.uint16)
    val_mask_slice = np.array(mask_arr[split_pos:], dtype=np.uint8)
    del ids_arr, mask_arr

    val_ids.write_bytes(val_ids_slice.tobytes())
    val_mask.write_bytes(val_mask_slice.tobytes())

    # Truncate train files to split_pos.
    with open(train_ids, "r+b") as f:
        f.truncate(split_pos * 2)  # uint16
    with open(train_mask, "r+b") as f:
        f.truncate(split_pos)  # uint8

    return split_pos, total - split_pos


# ---------------------------------------------------------------------------
# Manifest
# ---------------------------------------------------------------------------


def sha256_of_file(path: Path, chunk: int = 8 * 1024 * 1024) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            buf = f.read(chunk)
            if not buf:
                break
            h.update(buf)
    return h.hexdigest()


def write_manifest(
    out_dir: Path,
    alloc: dict[str, dict[str, int]],
    used_sources: list[str],
    train_tokens: int,
    val_tokens: int,
    per_source_lang_tokens: dict[tuple[str, str], int],
    langs: list[str],
    vocab_size: int,
) -> Path:
    src_meta = []
    for src_name in used_sources:
        try:
            src = sources.load(src_name)
            info = src.license_info()
        except (ValueError, ImportError):
            info = {"name": src_name, "license": "unknown"}
        try:
            info["task_type"] = src.task_type()
        except Exception:  # noqa: BLE001
            info["task_type"] = "unknown"
        info["tokens_per_lang"] = {
            lang: per_source_lang_tokens.get((src_name, lang), 0) for lang in langs
        }
        info["allocated_examples_per_lang"] = alloc.get(src_name, {})
        info["fetch_date"] = date.today().isoformat()
        src_meta.append(info)

    manifest = {
        "format_version": "sft-0.0.1",
        "created": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "vocab_size": vocab_size,
        "tokenizer": "../tokenizer.json",  # relative — shared with pretraining
        "langs": langs,
        "tokens": {
            "train": train_tokens,
            "val": val_tokens,
            "total": train_tokens + val_tokens,
        },
        "splits": {
            "train": {
                "ids":  {"path": "sft_train.bin",      "tokens": train_tokens, "dtype": "uint16",
                         "sha256": sha256_of_file(out_dir / "sft_train.bin")},
                "mask": {"path": "sft_train_mask.bin", "tokens": train_tokens, "dtype": "uint8",
                         "sha256": sha256_of_file(out_dir / "sft_train_mask.bin")},
            },
            "val": {
                "ids":  {"path": "sft_val.bin",      "tokens": val_tokens, "dtype": "uint16",
                         "sha256": sha256_of_file(out_dir / "sft_val.bin")},
                "mask": {"path": "sft_val_mask.bin", "tokens": val_tokens, "dtype": "uint8",
                         "sha256": sha256_of_file(out_dir / "sft_val_mask.bin")},
            },
        },
        "sources": src_meta,
        "compliance": {
            "ai_act_art_53": (
                "Per-source license + URL + fetch date + token + example counts "
                "are recorded in this manifest, satisfying the AI Act Art. 53 "
                "'sufficiently detailed summary' requirement for SFT data."
            ),
            "dataset_licenses": (
                "All SFT sources are under EU-compatible open licenses: "
                "Apache 2.0 (Glaive v2, Hermes-FC, OASST2, Aya, hand-written) "
                "and CC-BY-4.0 (xLAM). No OpenAI-output-derived datasets "
                "(Alpaca, ShareGPT, OpenOrca-derivatives) are included — their "
                "terms-of-use would be incompatible with the GPAI copyright "
                "compliance policy."
            ),
            "gdpr": (
                "Conversational sources contain prompter-supplied text; no "
                "deliberate inclusion of personal data. Aya and OASST2 are "
                "human-contributed under consent; xLAM/Glaive/Hermes are "
                "synthetic. Hand-written examples avoid real-person identifiers."
            ),
        },
        "loss_mask_convention": (
            "Each *_mask.bin is uint8, parallel to *_train.bin / *_val.bin. "
            "mask[i] == 1 iff token i is an assistant-generated target token "
            "(including the closing <|im_end|>). The loader applies the X→Y "
            "shift; the on-disk mask is NOT pre-shifted."
        ),
        "notes": (
            "Phase 2 EuroAgent SFT v0.1. DE + EN, agentic + tool-calling. "
            "Sized ~50–80 M tokens (~1–2 % of the 5 B-token pretraining corpus). "
            "Native-DE tool-calling coverage is the weakest spot — primarily "
            "hand_written + OASST2 — and is a candidate for translation-augmented "
            "expansion once a high-quality DE-MT pipeline is online."
        ),
    }
    path = out_dir / "manifest.json"
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _dry_run(alloc: dict[str, dict[str, int]], langs: list[str]) -> None:
    print("[sft-prepare] dry-run: probing each source for one example per lang...")
    for src_name in alloc:
        try:
            src = sources.load(src_name)
        except ValueError as e:
            print(f"  [err] cannot load {src_name}: {e}")
            continue
        print(f"  {src_name} ({src.task_type()}):")
        for lang in langs:
            if lang not in src.supported_langs():
                print(f"    [skip] {lang}: not supported by {src_name}")
                continue
            try:
                it = src.iter_examples(lang, 1)
                conv = next(it, None)
                if conv is None:
                    print(f"    [warn] {lang}: no examples returned")
                else:
                    n_msgs = len(conv.messages)
                    n_tc = sum(len(m.tool_calls) for m in conv.messages)
                    n_chars = sum(len(m.content) for m in conv.messages)
                    print(f"    [ok]   {lang}: {n_msgs} msgs, {n_tc} tool_calls, {n_chars} chars")
            except Exception as e:  # noqa: BLE001
                print(f"    [err]  {lang}: {type(e).__name__}: {e}")
    print("[sft-prepare] dry-run done")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--langs", nargs="+", default=DEFAULT_LANGS)
    ap.add_argument("--sources", nargs="+", default=list(DEFAULT_ALLOC_COUNT),
                    choices=sources.all_source_names())
    ap.add_argument("--alloc", type=Path, default=None,
                    help="Optional JSON file overriding per-source per-lang example counts.")
    ap.add_argument("--val-fraction", type=float, default=0.02,
                    help="Fraction of conversations (by token count, conv-aligned) to hold out for val.")
    ap.add_argument("--batch-size", type=int, default=64,
                    help="Conversations per tokenize batch.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Probe each source for one example; write nothing.")
    args = ap.parse_args()

    alloc = {k: dict(v) for k, v in DEFAULT_ALLOC_COUNT.items() if k in args.sources}
    if args.alloc:
        override = json.loads(args.alloc.read_text(encoding="utf-8"))
        for src_name, lang_budgets in override.items():
            if src_name in alloc:
                alloc[src_name].update(lang_budgets)
            else:
                alloc[src_name] = lang_budgets
    alloc = {s: {l: c for l, c in d.items() if l in args.langs} for s, d in alloc.items()}

    print("[sft-prepare] allocation (examples per source × lang):")
    for src_name, lang_budgets in alloc.items():
        total = sum(lang_budgets.values())
        print(f"  {src_name}: {total:,} convs across {sorted(lang_budgets)}")
    print(f"  TOTAL: {sum(sum(d.values()) for d in alloc.values()):,} target conversations")

    if args.dry_run:
        _dry_run(alloc, args.langs)
        return

    tok_path = pretrain_tokenizer_path()
    if not tok_path.exists():
        sys.exit(
            f"[sft-prepare] FATAL: pretraining tokenizer not found at {tok_path}\n"
            "Run `python -m dllm.data.prepare` first (or --reuse-tokenizer with an existing one)."
        )

    from tokenizers import Tokenizer  # noqa: PLC0415
    tokenizer = Tokenizer.from_file(str(tok_path))
    vocab_size = tokenizer.get_vocab_size()
    print(f"[sft-prepare] loaded pretrain tokenizer (vocab_size={vocab_size})")

    out = cache_dir()
    print(f"[sft-prepare] output dir: {out}")
    train_ids = out / "sft_train.bin"
    train_mask = out / "sft_train_mask.bin"
    val_ids = out / "sft_val.bin"
    val_mask = out / "sft_val_mask.bin"
    for p in (train_ids, train_mask, val_ids, val_mask):
        if p.exists():
            p.unlink()

    print("[sft-prepare] tokenize: parallel producers → encode_batch → disk")
    total_tokens, per_pair, boundaries = stream_tokenize_to_disk(
        alloc, args.langs, tokenizer, train_ids, train_mask,
        batch_size=args.batch_size,
    )
    print(f"  total tokens: {total_tokens:,} across {len(boundaries) - 1:,} conversations")
    for (src_name, lang), n in sorted(per_pair.items()):
        print(f"    {src_name} {lang}: {n:,} tokens")

    print(f"[sft-prepare] split: val_fraction={args.val_fraction}")
    train_n, val_n = split_at_boundary(
        train_ids, train_mask, val_ids, val_mask, boundaries, args.val_fraction,
    )
    print(f"  train: {train_n:,} tokens")
    print(f"  val:   {val_n:,} tokens")

    print("[sft-prepare] writing manifest")
    manifest_path = write_manifest(
        out, alloc, list(alloc), train_n, val_n, per_pair, args.langs, vocab_size,
    )
    print(f"  wrote {manifest_path}")
    print("[sft-prepare] done")


if __name__ == "__main__":
    main()
